"""initial schema

Revision ID: d51ceba2a034
Revises: 
Create Date: 2026-08-17 20:45:48.915775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51ceba2a034'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_de', sa.String(length=120), nullable=False),
    sa.Column('name_scientific', sa.String(length=160), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('VOGEL', 'FISCH', 'INSEKT', 'SAEUGETIER', 'SONSTIGES_LANDTIER', name='animalcategory'), nullable=False),
    sa.Column('habitat', sa.Text(), nullable=False),
    sa.Column('conservation_status', sa.String(length=120), nullable=False),
    sa.Column('reproduction_mode', sa.Enum('EGG_LAYING', 'LIVE_BEARING', name='reproductionmode'), nullable=False),
    sa.Column('offspring_count', sa.String(length=60), nullable=False),
    sa.Column('gestation_period', sa.String(length=60), nullable=False),
    sa.Column('diet', sa.Text(), nullable=False),
    sa.Column('natural_enemies', sa.Text(), nullable=False),
    sa.Column('social_behavior', sa.Enum('SOLITARY', 'HERD', name='socialbehavior'), nullable=False),
    sa.Column('group_size', sa.String(length=60), nullable=True),
    sa.Column('character_traits', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_category'), 'animals', ['category'], unique=False)
    op.create_index(op.f('ix_animals_name_de'), 'animals', ['name_de'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_daily_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assigned_date', name='uq_user_daily_animal')
    )
    op.create_index(op.f('ix_user_daily_animal_assigned_date'), 'user_daily_animal', ['assigned_date'], unique=False)
    op.create_index(op.f('ix_user_daily_animal_user_id'), 'user_daily_animal', ['user_id'], unique=False)
    op.create_table('user_quiz_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('last_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'animal_id', name='uq_user_quiz_progress')
    )
    op.create_index(op.f('ix_user_quiz_progress_animal_id'), 'user_quiz_progress', ['animal_id'], unique=False)
    op.create_index(op.f('ix_user_quiz_progress_next_due_at'), 'user_quiz_progress', ['next_due_at'], unique=False)
    op.create_index(op.f('ix_user_quiz_progress_user_id'), 'user_quiz_progress', ['user_id'], unique=False)
    op.create_table('user_seen_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'animal_id', name='uq_user_seen_animal')
    )
    op.create_index(op.f('ix_user_seen_animals_animal_id'), 'user_seen_animals', ['animal_id'], unique=False)
    op.create_index(op.f('ix_user_seen_animals_user_id'), 'user_seen_animals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_seen_animals_user_id'), table_name='user_seen_animals')
    op.drop_index(op.f('ix_user_seen_animals_animal_id'), table_name='user_seen_animals')
    op.drop_table('user_seen_animals')
    op.drop_index(op.f('ix_user_quiz_progress_user_id'), table_name='user_quiz_progress')
    op.drop_index(op.f('ix_user_quiz_progress_next_due_at'), table_name='user_quiz_progress')
    op.drop_index(op.f('ix_user_quiz_progress_animal_id'), table_name='user_quiz_progress')
    op.drop_table('user_quiz_progress')
    op.drop_index(op.f('ix_user_daily_animal_user_id'), table_name='user_daily_animal')
    op.drop_index(op.f('ix_user_daily_animal_assigned_date'), table_name='user_daily_animal')
    op.drop_table('user_daily_animal')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_animals_name_de'), table_name='animals')
    op.drop_index(op.f('ix_animals_category'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
